name: Provision & Configure Multi-Cloud VMs

on:
  push:
    branches: [master]  # ✅ ici on change main -> master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform AWS
        run: |
          cd terraform/aws
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Terraform Azure
        run: |
          cd terraform/azure
          terraform init
          terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform GCP
        run: |
          cd terraform/gcp
          terraform init
          terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Générer inventaire Ansible
        run: python3 scripts/generate_inventory.py

      - name: Installer Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Déployer Nginx
        run: ansible-playbook -i ansible/inventory.ini ansible/nginx.yml
