name: Provision & Configure AWS VM with Nginx

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Provision AWS VM with Terraform
        run: |
          cd multi-cloud-nginx/terraform/aws
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Export AWS public IP to JSON
        run: |
          IP=$(terraform -chdir=multi-cloud-nginx/terraform/aws output -raw aws_public_ip)
          echo "{ \"aws\": \"$IP\" }" > multi-cloud-nginx/scripts/ips.json

      - name: Generate Ansible inventory
        run: |
          python3 multi-cloud-nginx/scripts/generate_inventory.py

      - name: Install Ansible
        run: |
          sudo apt-get update && sudo apt-get install -y ansible

      - name: Deploy Nginx via Ansible
        run: |
          ansible-playbook -i multi-cloud-nginx/ansible/inventory.ini multi-cloud-nginx/ansible/nginx.yml

      - name: Check Nginx is running
        run: |
          IP=$(jq -r '.aws' multi-cloud-nginx/scripts/ips.json)
          curl -I --connect-timeout 10 http://$IP | grep "200 OK"
