name: Provision & Configure AWS VM with Nginx

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform AWS
        run: |
          cd multi-cloud-nginx/terraform/aws
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Export AWS public IP to JSON
        run: |
          cd multi-cloud-nginx/terraform/aws
          terraform output -raw aws_public_ip > tmp_ip.txt
          IP=$(cat tmp_ip.txt | tr -d '\r\n')
          echo "{ \"aws\": \"${IP}\" }" > ../../scripts/ips.json

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Generate Ansible Inventory
        run: python3 multi-cloud-nginx/scripts/generate_inventory.py

      - name: Deploy Nginx with Ansible
        run: ansible-playbook -i multi-cloud-nginx/ansible/inventory.ini multi-cloud-nginx/ansible/nginx.yml
