name: Provision & Configure AWS VM with Nginx

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-north-1  # Changement de région

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/aws.pem
          chmod 600 ~/.ssh/aws.pem

      - name: Terraform Init & Apply
        run: |
          cd multi-cloud-nginx/terraform/aws
          terraform init
          terraform apply -auto-approve
          terraform output -raw public_ip > ../../scripts/ip.txt
          echo '{"aws":"$(cat ../../scripts/ip.txt)"}' > ../../scripts/ips.json

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          cd multi-cloud-nginx/ansible
          ansible-playbook -i inventory.ini nginx.yml --ssh-common-args='-o StrictHostKeyChecking=no'
